# Generated by Django 6.1.1 on 2026-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_payment_status_alter_cart_cod_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_wait_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
